### ISSUE TITLE
Import scripts don't rollback on error

### ISSUE THREAD

**Issue by philbooth** [mozilla/fxa-activity-metrics#63]
The import scripts run their queries in a transaction, which they rollback when exceptions are raised.

Or at least, that's the plan. I've never actually seen this work. Frequently I've seen errrors abort the import scripts, and the database is always left in whatever it state it was at the point where the offending query was exectuted.

Not sure if this is something related to redshift and transactions, or something we're doing wrong vis-à-vis Python's `postgres` package.

Example python error from one of these failures:

```
IMPORTING 2016-09-29
Traceback (most recent call last):
  File "./import_flow_events.py", line 274, in <module>
    EVENT_COLUMNS,
  File "/home/ec2-user/fxa-activity-metrics/import_events.py", line 240, in run
    import_day(day)
  File "/home/ec2-user/fxa-activity-metrics/import_events.py", line 184, in import_day
    **CONFIG))
  File "/usr/lib/python2.7/site-packages/postgres/__init__.py", line 374, in run
    cursor.run(sql, parameters)
  File "/usr/lib/python2.7/site-packages/postgres/cursors.py", line 92, in run
    self.execute(sql, parameters)
  File "/usr/lib64/python2.7/site-packages/psycopg2/extras.py", line 288, in execute
    return super(NamedTupleCursor, self).execute(query, vars)
psycopg2.InternalError: Load into table 'temporary_raw_flow_data' failed.  Check 'stl_load_errors' system table for details.
```

**Comment by philbooth** [comment]
Fwiw, in #62 I've removed the attempted transaction entirely. If we did get it to work, I can see it being really annoying if a big import got 90% of the way through before rolling back because of a problem.

On the odd occastions when an import error does occur, manually cleaning up isn't too tricky. And the import scripts clear each day before they do the import anyway so I don't think double-days are a possibility.

Given all of the above, I don't see any mileage in pursuing this so I'm closing it out. I'm happy to be disagreed with if anyone wants to repoen this though.
